In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans

pd.options.display.max_columns = None
pd.options.display.max_rows = None

<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject

In [6]:
df = pd.read_csv('SCA.csv')
df.head()

,Player,Nation,Pos,Squad,90s,SCA,SCA90,PassLive,PassDead,Dribbles,Shots,Fouls,Def,GCA,GCA90
0,Patrick van Aanholt\Patrick-van-Aanholt,nl NED,DF,Crystal Palace,19.7,26,1.32,22,3,1,0,0,0,3,0.15
1,Tammy Abraham\Tammy-Abraham,eng ENG,FW,Chelsea,11.6,18,1.56,11,0,1,3,3,0,2,0.17
2,Che Adams\Che-Adams,sct SCO,FW,Southampton,29.6,66,2.23,48,0,1,6,8,3,8,0.27
3,Tosin Adarabioyo\Tosin-Adarabioyo,eng ENG,DF,Fulham,32.8,17,0.52,16,0,0,1,0,0,1,0.03
4,Adrián\Adrian,es ESP,GK,Liverpool,3.0,0,0.00,0,0,0,0,0,0,0,0.00

In [7]:
df['Player'] = df['Player'].str.split('\\',expand=True)[0]

df['Nation'] = df['Nation'].str.split(' ',expand = True)[1]

df['Pos'] = df['Pos'].str[:2]

df.head()

,Player,Nation,Pos,Squad,90s,SCA,SCA90,PassLive,PassDead,Dribbles,Shots,Fouls,Def,GCA,GCA90
0,Patrick van Aanholt,NED,DF,Crystal Palace,19.7,26,1.32,22,3,1,0,0,0,3,0.15
1,Tammy Abraham,ENG,FW,Chelsea,11.6,18,1.56,11,0,1,3,3,0,2,0.17
2,Che Adams,SCO,FW,Southampton,29.6,66,2.23,48,0,1,6,8,3,8,0.27
3,Tosin Adarabioyo,ENG,DF,Fulham,32.8,17,0.52,16,0,0,1,0,0,1,0.03
4,Adrián,ESP,GK,Liverpool,3.0,0,0.00,0,0,0,0,0,0,0,0.00

In [ ]:
add_list = ['PassLive']